SME_ARCHETYPES = {
    "greenhouse_vegetable_sme": {
        "production_volume": 1800,
        "delivery_batch_size": 140,
        "shelf_life_days": 5,
        "base_unit_margin_eur": 1.10,
        "cash_buffer_periods": 3,
        "digital_capability": 0.62,
        "collaboration_willingness": 0.68,
        "trust_level": 0.50,
        "quality_compliance": 0.82,
        "logistics_competence": 0.72,
        "channel_management_capacity": 3,
        "risk_aversion": 0.42,
        "dependency_tolerance": 0.45,
        "learning_rate": 0.18,
        "preferred_channels": ["retail", "horeca", "hub"],
    },
    "farm_shop_restaurant_sme": {
        "production_volume": 650,
        "delivery_batch_size": 55,
        "shelf_life_days": 12,
        "base_unit_margin_eur": 3.40,
        "cash_buffer_periods": 5,
        "digital_capability": 0.55,
        "collaboration_willingness": 0.52,
        "trust_level": 0.58,
        "quality_compliance": 0.78,
        "logistics_competence": 0.60,
        "channel_management_capacity": 4,
        "risk_aversion": 0.48,
        "dependency_tolerance": 0.20,
        "learning_rate": 0.14,
        "preferred_channels": ["direct", "farm_shop", "restaurant", "public"],
    },
    "fish_farming_sme": {
        "production_volume": 1100,
        "delivery_batch_size": 95,
        "shelf_life_days": 6,
        "base_unit_margin_eur": 2.20,
        "cash_buffer_periods": 4,
        "digital_capability": 0.66,
        "collaboration_willingness": 0.44,
        "trust_level": 0.47,
        "quality_compliance": 0.90,
        "logistics_competence": 0.81,
        "channel_management_capacity": 2,
        "risk_aversion": 0.57,
        "dependency_tolerance": 0.36,
        "learning_rate": 0.12,
        "preferred_channels": ["retail", "horeca", "industry"],
    },
}
